Repository toothring/TheThingDoers, pull requests merged in 2019-11, with the labels that each got.

#10 Huge Refactor
  build/built-jar.properties
  deps/LibOrion.jar
  dist/TetrisTestGround.jar
  nbproject/build-impl.xml
  nbproject/genfiles.properties
  nbproject/project.properties
  nbproject/project.xml
  src/testjfxapp/MainMenu.java
  src/testjfxapp/TestJFXApp.java
  src/testjfxapp/TetrisBlock.java
Labels: Bug, Dependencies, documentation, enhancement

#11 Wonderful wonderful audio
  audiodata/testjfxapp/audiodata/levelDone.mp3
  audiodata/testjfxapp/audiodata/main.mp3
  build/built-jar.properties
  dist/TetrisTestGround.jar
  nbproject/build-impl.xml
  nbproject/genfiles.properties
  nbproject/private/private.xml
  nbproject/project.properties
  nbproject/project.xml
  src/testjfxapp/MainMenu.java
  src/testjfxapp/subsystems/AudioSubsystem.java
Labels: enhancement

#13 Merge Brendan's branch onto master
  .idea/libraries/lib.xml
  .idea/misc.xml
  audiodata/testjfxapp/audiodata/levelDone.mp3
  audiodata/testjfxapp/audiodata/main.mp3
  bin/.idea/libraries/lib.xml
  bin/.idea/misc.xml
  bin/META-INF/Tetsaw.kotlin_module
  bin/build.xml
  bin/manifest.mf
  bin/nbproject/private/private.properties
  bin/testjfxapp/TestJFXApp.class
  bin/testjfxapp/TetrisBlock.class
  build/built-jar.properties
  dist/TetrisTestGround.jar
  nbproject/build-impl.xml
  nbproject/genfiles.properties
  nbproject/private/private.xml
  nbproject/project.properties
  nbproject/project.xml
  src/testjfxapp/GraphicsOptions.java
  src/testjfxapp/InGameMenu.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Settings.java
  src/testjfxapp/TestJFXApp.java
  src/testjfxapp/subsystems/AudioSubsystem.java
Labels: enhancement, help wanted

#16 Fix a boo-boo
  build/built-jar.properties
  nbproject/private/private.xml
  src/testjfxapp/subsystems/AudioSubsystem.java
Labels: Bug

#17 Adds buttons to return to the previous menu screen in the options menu
  build/built-jar.properties
  src/testjfxapp/AccessibilSettings.java
  src/testjfxapp/AudioSettings.java
  src/testjfxapp/GraphicsOptions.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/ReversableMenu.java
  src/testjfxapp/Settings.java
Labels: Incomprehensible Magic, enhancement

#18 This adds all those classes for the menu items and the stuff that Callum fixed :)
  bin/build/built-jar.properties
  bin/nbproject/private/private.xml
Labels: Bug?, Configuration

#19 Refactor for sanity
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Tetris.java
Labels: Refactor

#21 Bb
  src/testjfxapp/InGameMenu.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Tetris.java
Labels: Merge Conflict, enhancement

#22 Bb
  src/testjfxapp/InGameMenu.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Tetris.java
Labels: enhancement

#23 Bb
  src/testjfxapp/AccessibilSettings.java
  src/testjfxapp/AudioSettings.java
  src/testjfxapp/GraphicsOptions.java
  src/testjfxapp/InGameMenu.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Scoreboard.java
  src/testjfxapp/Tetris.java
Labels: enhancement

#24 Row removal mike
  build/built-jar.properties
  nbproject/private/private.xml
  src/testjfxapp/Tetris.java
  src/testjfxapp/TetrisBlock.java
Labels: Incomprehensible Magic, enhancement

#25 Bb
  src/testjfxapp/Scoreboard.java
  src/testjfxapp/Tetris.java
Labels: Merge Conflict, enhancement

#27 Made tons of stuff static and added playback multipliers
  src/testjfxapp/subsystems/AudioSubsystem.java
Labels: enhancement

#36 Tetsawwwwwwwyeah
  .gitignore
  build/built-jar.properties
  images/test2.png
  src/testjfxapp/Data.java
  src/testjfxapp/InGameMenu.java
  src/testjfxapp/MainMenu.java
  src/testjfxapp/Tetris.java
  src/testjfxapp/TetrisBlock.java
  src/testjfxapp/Tetsaw.java
  src/testjfxapp/TetsawBlock.java
  src/testjfxapp/TetsawBlockData.java
  src/testjfxapp/TetsawLevelData.java
  src/testjfxapp/TetsawStylesheet.css
  src/testjfxapp/subsystems/AudioSubsystem.java
Labels: Incomprehensible Magic, enhancement

#37 Butoons
  build/built-jar.properties
  src/testjfxapp/MainMenu.java
Labels: enhancement

#40 Fix another higgs bugson
  src/testjfxapp/Tetris.java
Labels: Bug?, Incomprehensible Magic, enhancement
